version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - mv /root/.m2/repository/com/devops4solutions/LoginWebApp/1//LoginWebApp-1.war dist/LoginWebApp-1.war
artifacts:
  files:
    - dist/LoginWebApp-1.war
